Update flutter-android.yml

diff --git a/.github/workflows/flutter-android.yml b/.github/workflows/flutter-android.yml
--- a/.github/workflows/flutter-android.yml
+++ b/.github/workflows/flutter-android.yml
@@ -7,23 +7,34 @@ on:
 
 jobs:
   build:
-    name: Build APK
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Repo
+      - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up Flutter
+      - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.22.0'
 
-      - name: Install Dependencies
+      - name: Install dependencies
         run: flutter pub get
+
+      - name: Debug flutter env
+        run: flutter doctor -v
 
       - name: Build APK
         run: flutter build apk --release
+
+      - name: Check APK exists
+        run: |
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "❌ APK not found!"
+            exit 1
+          else
+            echo "✅ APK found"
+          fi
 
       - name: Upload APK Artifact
         uses: actions/upload-artifact@v4
